export default function getUserDeviceInfo(openid){
  const res = {}
  res.sceneList = [
    {
      position:'common',
      name:'常用',
      equipmentList:[
        {
          name:'智能空调',
          position:'客厅',
          img:'',
          linkType:1
        },
        {
          name:'智能门锁',
          position:'客厅',
          img:'',
          linkType:0
        },
        {
          name:'智能湿度传感器',
          position:'客厅',
          img:'',
          linkType:2
        },
        {
          name:'LED灯泡',
          position:'客厅',
          img:'',
          linkType:1
        },
        {
          name:'智能扫地机器人',
          position:'客厅',
          img:'',
          linkType:3
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
      ]
    },
    {
      position:'livingroom',
      name:'客厅',
      equipmentList:[
        {
          name:'智能空调',
          position:'客厅',
          img:'',
          linkType:1
        },
        {
          name:'智能门锁',
          position:'客厅',
          img:'',
          linkType:0
        },
        {
          name:'智能湿度传感器',
          position:'客厅',
          img:'',
          linkType:2
        },
        {
          name:'LED灯泡',
          position:'客厅',
          img:'',
          linkType:1
        },
        {
          name:'智能扫地机器人',
          position:'客厅',
          img:'',
          linkType:3
        }
      ]
    },
    {
      position:'bedroom',
      name:'卧室',
      equipmentList:[
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
      ]
    },
    {
      position:'canteen',
      name:'餐厅',
      equipmentList:[
        {
          name:'智能空气净化器',
          position:'餐厅',
          img:'',
          linkType:1
        },
      ]
    },
    {
      position:'restroom',
      name:'卫生间',
      equipmentList:[
        {
          name:'智能空气净化器',
          position:'卧室',
          img:'',
          linkType:1
        },
      ]
    }
  ]
  return Promise.resolve(res);
}